"""Writes the drawing statements of the listing (the HPLOT lines of the overworld, the dungeon walls and
the monsters) into src/app/renderers/drawing-programs.ts, so the renderers draw from the program's own
coordinate expressions and nothing is transcribed by hand.

Usage: ./fetch-listing.sh && python3 generate_drawing_programs.py
"""
import re
from pathlib import Path

from listing import corrected_lines

OUT = Path(__file__).resolve().parents[2] / 'src' / 'app' / 'renderers' / 'drawing-programs.ts'
KEPT = re.compile(r'^(HPLOT\b|(BASE|TP|LX|RX|Y\d)\s*=)')


def statements_of(line: str) -> list:
    body = line.strip()
    if ' THEN ' in f' {body} ':
        body = re.split(r'\bTHEN\b', body, maxsplit=1)[1]
    kept = []
    for statement in body.split(':'):
        statement = statement.strip()
        if KEPT.match(statement):
            kept.append(re.sub(r'\s+', ' ', statement))
    return kept


def main() -> None:
    lines = corrected_lines()
    wanted = [105, 120, 130, 140, 150, 160, 170, 210, 214, 216, 218, 220, 222, 224, 226, 230, 232, 236, 238, 240, 242,
              244, 246, 248, 250, 252]
    wanted += list(range(300, 306)) + [310, 311, 312] + list(range(320, 324)) + list(range(330, 337))
    wanted += list(range(340, 347)) + list(range(350, 356)) + [360, 361, 362, 370, 371, 372]
    wanted += list(range(380, 387)) + [3087, 3088, 3089] + list(range(390, 401))
    out = ['// Generated by tools/oracle/generate_drawing_programs.py from the listing\'s drawing lines.',
           '// Each entry is what one BASIC line draws, keyed by its line number.', '',
           'export const DRAWING_LINES: Readonly<Record<number, readonly string[]>> = {']
    for number in wanted:
        statements = statements_of(lines[number])
        assert statements, number
        out.append(f'  {number}: [')
        out.extend(f"    '{statement}'," for statement in statements)
        out.append('  ],')
    out.append('};')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(out) + '\n')
    print(f'{len(wanted)} lines')


if __name__ == '__main__':
    main()
