"""Records Akalabeth running on the real Apple II+ ROMs, for the port's differential specs.

Usage: ./build-rom.sh && ./fetch-listing.sh && python3 generate_game_fixtures.py

Writes src/app/port/fixtures/:
  tables.json       the perspective tables XX% YY% PER% LD% CD% FT% LAD% (they do not depend on the seed)
  worlds.json       per lucky number: the 20x20 terrain, the starting square and the rolled stats
  dungeons.json     per lucky number, dungeon square and level: DNG%, the float DNG array line 520
                    writes, monster positions and hit points
  sessions/*.json   scripted games, one screen state per key

The program is loaded at $4001, above the hi-res page it draws on, as the original disk had to.
"""
import base64
import hashlib
import json
import pickle
import random
import sys
import zlib
from collections import deque
from pathlib import Path

from apple2_machine import Apple2
from listing import program_text

HERE = Path(__file__).resolve().parent
OUT = HERE.parents[1] / 'src' / 'app' / 'port' / 'fixtures'
TYPED_PREFIX = 'typed-program-'

RETURN, RIGHT, LEFT, ESCAPE, CTRL_C = 0x0D, 0x15, 0x08, 0x1B, 0x03
NORTH, EAST, WEST, SOUTH = RETURN, RIGHT, LEFT, ord('/')
FORWARD, TURN_RIGHT, TURN_LEFT, TURN_AROUND = RETURN, RIGHT, LEFT, ord('/')


def packed_to_number(packed: str) -> float:
    data = bytes.fromhex(packed)
    if data[0] == 0:
        return 0.0
    mantissa = ((data[1] | 0x80) << 24) | (data[2] << 16) | (data[3] << 8) | data[4]
    value = mantissa * 2.0 ** (data[0] - 160)
    return -value if data[1] & 0x80 else value


def grid(array: dict) -> list:
    """Applesoft stores the first subscript fastest; return rows indexed [first][second]."""
    first, second = array['extents']
    return [[array['values'][x + first * y] for y in range(second)] for x in range(first)]


# --- machine lifecycle ---

def typed_machine() -> Apple2:
    machine = Apple2()
    digest = hashlib.sha256('\n'.join(program_text()).encode()).hexdigest()[:16]
    typed = HERE / 'rom' / f'{TYPED_PREFIX}{digest}.pkl'
    if typed.exists():
        machine.restore(pickle.loads(typed.read_bytes()))
    else:
        machine.reset()
        machine.run_until_idle(limit=20_000_000)
        machine.type_text('POKE 103,1:POKE 104,64:POKE 16384,0:NEW\r')
        machine.type_text('\r'.join(program_text()) + '\r')
        typed.write_bytes(pickle.dumps(machine.snapshot()))
    return machine


def press(machine: Apple2, *keys) -> None:
    for key in keys:
        if isinstance(key, str):
            machine.keys.extend(ord(character) for character in key)
        else:
            machine.keys.append(key)
    machine.run_until_idle()


def screen_text(machine: Apple2) -> str:
    return '\n'.join(machine.text_lines())


def new_game(lucky: str, level: str = '1', stats_answers: str = 'Y', kind: str = 'F', shopping: str = 'Q') -> Apple2:
    machine = typed_machine()
    press(machine, 'RUN\r', lucky + '\r', level + '\r', stats_answers, kind, shopping)
    return machine


# --- worlds and tables ---

def record_tables(machine: Apple2) -> dict:
    arrays = machine.arrays()
    return {name: arrays[key]['values'] if len(arrays[key]['extents']) == 1 else grid(arrays[key])
            for name, key in [('XX', 'XX%'), ('YY', 'YY%'), ('PER', 'PE%'), ('LD', 'LD%'), ('CD', 'CD%'),
                              ('FT', 'FT%'), ('LAD', 'LA%')]}


def record_world(machine: Apple2, lucky: str) -> dict:
    arrays = machine.arrays()
    variables = machine.simple_variables()
    return {
        'lucky': lucky,
        'terrain': grid(arrays['TE%']),
        'start': [packed_to_number(variables['TX']), packed_to_number(variables['TY'])],
        'stats': [packed_to_number(value) for value in arrays['C']['values']],
        'statsPacked': arrays['C']['values'],
    }


# --- dungeons, generated by the program's own GOSUB 500 in direct mode ---
# Ctrl-C cannot reach direct mode once the program runs: ONERR GOTO 4 catches it and restarts.
# So the dungeon generator is called before RUN, with the arrays it uses dimensioned as line 20
# and line 60041 do, and the variables it reads set as play would leave them.

def dungeon_machine(lucky: str, level_of_play: str) -> Apple2:
    machine = typed_machine()
    press(machine, f'DIM DN%(10,10),ML%(10,1),MZ%(10,1):LN={lucky}:LP={level_of_play}\r')
    return machine


def record_dungeon(machine: Apple2, tx: int, ty: int, level: int) -> dict:
    press(machine, f'PX=1:PY=1:TX={tx}:TY={ty}:IN={level}:GOSUB 500\r')
    arrays = machine.arrays()
    variables = machine.simple_variables()
    record = {
        'square': [tx, ty],
        'level': level,
        'dng': grid(arrays['DN%']),
        'monsterAt': grid(arrays['ML%']),
        'monster': grid(arrays['MZ%']),
        'count': packed_to_number(variables['NM']),
    }
    if 'DN' in arrays:
        record['floatDng'] = grid(arrays['DN'])
    return record


def squares(world: dict, kind: int) -> list:
    return [[x, y] for x in range(21) for y in range(21) if world['terrain'][x][y] == kind]


# --- sessions ---

class Recorder:
    def __init__(self, machine: Apple2) -> None:
        self.machine = machine
        self.steps = []
        self.previous_text = [''] * 24
        self.previous_inverse = [''] * 24
        self.previous_mode = None
        self.previous_hires = None
        self.errors = []
        self.setups = []
        machine.on_key = self.on_key
        machine.on_error = self.errors.append

    def state(self) -> dict:
        machine = self.machine
        record = {}
        text = machine.text_lines()
        inverse = machine.inverse_mask()
        changed = {row: text[row] for row in range(24) if text[row] != self.previous_text[row]}
        if changed:
            record['text'] = changed
        changed_inverse = {row: inverse[row] for row in range(24) if inverse[row] != self.previous_inverse[row]}
        if changed_inverse:
            record['inverse'] = changed_inverse
        mode = ('GRAPHICS' if machine.graphics else 'TEXT') + ('+MIXED' if machine.mixed else '') + \
               ('+HIRES' if machine.hires else '') + ('+PAGE2' if machine.page2 else '')
        if mode != self.previous_mode:
            record['mode'] = mode
        hires = machine.hires_page()
        if hires != self.previous_hires:
            record['hires'] = base64.b64encode(zlib.compress(hires, 9)).decode('ascii')
        if self.errors:
            record['errors'] = self.errors[:]
            self.errors.clear()
        self.previous_text, self.previous_inverse, self.previous_mode, self.previous_hires = text, inverse, mode, hires
        return record

    def on_key(self, key: int) -> None:
        record = self.state()
        record['key'] = key | 0x80
        self.steps.append(record)

    def finish(self) -> list:
        self.steps.append(self.state())
        self.machine.on_key = None
        return self.steps


def path_to(world: dict, start: list, kind: int) -> tuple:
    """Overworld keys along a shortest walk to the nearest square of a kind, round the mountains,
    and the square it ends on."""
    start = [int(value) for value in start]
    moves = [(0, -1, NORTH), (1, 0, EAST), (-1, 0, WEST), (0, 1, SOUTH)]
    seen = {tuple(start): []}
    queue = deque([tuple(start)])
    while queue:
        x, y = queue.popleft()
        if world['terrain'][x][y] == kind and [x, y] != start:
            return seen[(x, y)], [x, y]
        for dx, dy, key in moves:
            nx, ny = x + dx, y + dy
            if (nx, ny) not in seen and world['terrain'][nx][ny] != 1:
                seen[(nx, ny)] = seen[(x, y)] + [key]
                queue.append((nx, ny))
    raise ValueError(f'no square of kind {kind} reachable')


def started_session(lucky: str, level: str, stats_answers: str, kind: str, shopping: str):
    machine = typed_machine()
    press(machine, 'RUN\r')
    recorder = Recorder(machine)
    press(machine, lucky + '\r', level + '\r', stats_answers, kind, shopping)
    world = record_world(machine, lucky)
    return machine, recorder, world


def dungeon_policy(machine: Apple2, rng: random.Random, kind: str, keys: int) -> None:
    for _ in range(keys):
        screen = screen_text(machine)
        if 'HIT ESC KEY' in screen:
            press(machine, ESCAPE)
            return
        if 'TO CONT' in screen or 'TO CONTINUE' in screen:
            press(machine, RETURN)
            continue
        roll = rng.random()
        if roll < 0.40:
            press(machine, FORWARD)
        elif roll < 0.55:
            press(machine, rng.choice([TURN_RIGHT, TURN_LEFT, TURN_AROUND]))
        elif roll < 0.62:
            press(machine, 'X')
        elif roll < 0.92:
            weapon = rng.choice('RASBM' if kind == 'F' else 'ASM')
            press(machine, 'A', weapon)
            if weapon == 'A':
                press(machine, rng.choice('TS'))
            if weapon == 'M' and kind == 'M' and 'CHOICE' in screen_text(machine):
                press(machine, rng.choice('1234'))
        elif roll < 0.96:
            press(machine, ' ')
        else:
            press(machine, 'S', RETURN)


def session_creation() -> dict:
    machine, recorder, world = started_session('7', '3', 'NNY', 'XM', 'FFRBASMZQ')
    press(machine, 'S', 'HELLO\r', 'P', 'P', ' ', 'H', 'K')
    return {'name': 'creation', 'lucky': '7', 'steps': recorder.finish()}


def session_overworld() -> dict:
    machine, recorder, world = started_session('1', '1', 'Y', 'F', 'FRAQ')
    keys, town = path_to(world, world['start'], 3)
    press(machine, *keys, 'X', 'FFSBQ')
    keys, _castle = path_to(world, town, 5)
    press(machine, *keys)
    press(machine, 'X', 'AVATAR\r', 'Y', ' ')
    press(machine, 'X', ' ')
    press(machine, NORTH, EAST, SOUTH, WEST)
    return {'name': 'overworld', 'lucky': '1', 'steps': recorder.finish()}


def session_dungeon(lucky: str, kind: str, shopping: str, seed: int, keys: int) -> dict:
    machine, recorder, world = started_session(lucky, '2', 'Y', kind, shopping)
    walk, _dungeon = path_to(world, world['start'], 4)
    press(machine, *walk, 'X')
    dungeon_policy(machine, random.Random(seed), kind, keys)
    return {'name': f'dungeon-{kind.lower()}-{lucky}', 'lucky': lucky, 'steps': recorder.finish()}


def session_knighthood() -> dict:
    machine, recorder, world = started_session('3', '1', 'Y', 'F', 'FFFFFFQ')
    keys, _castle = path_to(world, world['start'], 5)
    press(machine, *keys, 'X', 'ARTHUR\r', 'Y', ' ')
    # Debugger-style setup: all ten quests done, then report back.
    machine.set_simple_variable('TA', bytes([0x84, 0xA0, 0x00, 0x00, 0x00]))
    press(machine, 'X', ' ')
    return {'name': 'knighthood', 'lucky': '3', 'setup': 'TASK set to -10 in memory before the second visit',
            'steps': recorder.finish()}


INPUT_LINES = ['7', '  5', '1,2', 'a:b', '"7"', '"7', '12abc', '-3', '1e2', '.5', '', '  ', '1 2', ' -1.5E1',
               '+4', '0', '1,', ':', '"a,b",3', '1979', '65535', '2.5', '-0.25', 'abc', '1E', '1E+', '--1',
               'ab\x08c', '12\x185', '\x085', 'ab\x08\x08\x08c', '1.2.3', '0.000001', '12345678901', '1,2,3']


def record_input(typed: str) -> dict:
    machine = typed_machine()
    press(machine, 'RUN\r', typed + '\r')
    variables = machine.simple_variables()
    return {
        'typed': typed,
        'string': variables.get('Q$'),
        'lucky': variables.get('LN'),
        'rows': [row.rstrip() for row in machine.text_lines()[3:9]],
    }

# --- scenarios that steer the game with what is in its memory ---

def player(machine: Apple2) -> tuple:
    variables = machine.simple_variables()
    return tuple(int(packed_to_number(variables[name])) for name in ['PX', 'PY', 'DX', 'DY', 'IN'])


def dungeon_grid(machine: Apple2) -> list:
    return grid(machine.arrays()['DN%'])


def monsters_in_play(machine: Apple2) -> list:
    arrays = machine.arrays()
    alive, where = grid(arrays['MZ%']), grid(arrays['ML%'])
    return [(number, where[number][0], where[number][1]) for number in range(1, 11) if alive[number][0] == 1]


def turn_right(dx: int, dy: int) -> tuple:
    return (0, dx) if dx != 0 else (-dy, 0)


def turn_left(dx: int, dy: int) -> tuple:
    return (0, -dx) if dx != 0 else (dy, 0)


def plan_to(machine: Apple2, tiles: list, avoid_traps: bool = True):
    """The first key of a shortest walk to a square whose tile is in `tiles`, or None."""
    x, y, dx, dy, _level = player(machine)
    dn = dungeon_grid(machine)
    start = (x, y, dx, dy)
    seen = {start: None}
    queue = deque([start])
    while queue:
        node = queue.popleft()
        px, py, ddx, ddy = node
        if node != start or dn[px][py] in tiles:
            if dn[px][py] in tiles and (px, py) != (x, y):
                first = node
                while seen[first][0] != start:
                    first = seen[first][0]
                return seen[first][1]
        options = [(TURN_RIGHT, (px, py) + turn_right(ddx, ddy)), (TURN_LEFT, (px, py) + turn_left(ddx, ddy)),
                   (TURN_AROUND, (px, py, -ddx, -ddy))]
        ahead = (px + ddx, py + ddy)
        if 0 <= ahead[0] <= 10 and 0 <= ahead[1] <= 10:
            cell = dn[ahead[0]][ahead[1]]
            if cell != 1 and cell < 10 and (cell != 2 or not avoid_traps or 2 in tiles):
                options.append((FORWARD, ahead + (ddx, ddy)))
        for key, nxt in options:
            if nxt not in seen:
                seen[nxt] = (node, key)
                queue.append(nxt)
    return None


def adjacent_monster(machine: Apple2):
    x, y, dx, dy, _level = player(machine)
    for number, mx, my in monsters_in_play(machine):
        if abs(mx - x) + abs(my - y) == 1:
            return number, (mx - x, my - y)
    return None


def face(machine: Apple2, wanted: tuple) -> None:
    _x, _y, dx, dy, _level = player(machine)
    if (dx, dy) == wanted:
        return
    if (-dx, -dy) == wanted:
        press(machine, TURN_AROUND)
    elif turn_right(dx, dy) == wanted:
        press(machine, TURN_RIGHT)
    else:
        press(machine, TURN_LEFT)


def is_over(machine: Apple2) -> bool:
    return 'HIT ESC KEY' in screen_text(machine)


def fight_if_attacked(machine: Apple2, weapon: str) -> bool:
    neighbour = adjacent_monster(machine)
    if neighbour is None or is_over(machine):
        return False
    face(machine, neighbour[1])
    press(machine, 'A', weapon)
    if weapon == 'A':
        press(machine, 'S')
    return True


def walk_to(machine: Apple2, tiles: list, weapon: str = 'R', limit: int = 160) -> bool:
    for _ in range(limit):
        screen = screen_text(machine)
        if is_over(machine):
            return False
        if 'TO CONT' in screen:
            press(machine, RETURN)
            continue
        x, y, _dx, _dy, _level = player(machine)
        if dungeon_grid(machine)[x][y] in tiles:
            return True
        if fight_if_attacked(machine, weapon):
            continue
        key = plan_to(machine, tiles, avoid_traps=2 not in tiles)
        if key is None:
            return False
        press(machine, key)
    return False


def poke_task(machine: Apple2, recorder: Recorder, value: int) -> None:
    """Debugger-style: sets TASK in memory; the spec sets it before the key that follows."""
    bits = abs(value).bit_length()
    mantissa = abs(value) << (32 - bits)
    first = ((mantissa >> 24) & 0x7F) | (0x80 if value < 0 else 0)
    machine.set_simple_variable('TA', bytes([0x80 + bits, first, (mantissa >> 16) & 0xFF, (mantissa >> 8) & 0xFF, mantissa & 0xFF]))
    recorder.setups.append({'beforeKey': len(recorder.steps), 'task': value})


def enter_first_dungeon(machine: Apple2, world: dict) -> None:
    walk, _dungeon = path_to(world, world['start'], 4)
    press(machine, *walk, 'X')


def finish(name: str, lucky: str, recorder: Recorder) -> dict:
    return {'name': name, 'lucky': lucky, 'setups': recorder.setups, 'steps': recorder.finish()}


def packed_integer(value: int) -> bytes:
    if value == 0:
        return bytes(5)
    bits = abs(value).bit_length()
    mantissa = abs(value) << (32 - bits)
    first = ((mantissa >> 24) & 0x7F) | (0x80 if value < 0 else 0)
    return bytes([0x80 + bits, first, (mantissa >> 16) & 0xFF, (mantissa >> 8) & 0xFF, mantissa & 0xFF])


def poke_cell(machine: Apple2, recorder: Recorder, array: str, index: int, value: int) -> None:
    """Debugger-style: one cell of C() or PW() set in memory. The spec repeats it before the next key."""
    machine.set_real_array_cell(array, [index], packed_integer(value))
    recorder.setups.append({'beforeKey': len(recorder.steps), 'array': array, 'index': index, 'value': value})


def poke_square(machine: Apple2, recorder: Recorder, x: int, y: int, value: int) -> None:
    """Debugger-style: one square of DNG%() set in memory. The spec repeats it before the next key."""
    machine.set_integer_array_cell('DN%', [x, y], value)
    recorder.setups.append({'beforeKey': len(recorder.steps), 'square': [x, y], 'value': value})


def session_gallery() -> dict:
    """Every monster at several distances down an opened corridor, for the renderers."""
    machine, recorder, world = started_session('10', '1', 'Y', 'F', 'FQ')
    enter_first_dungeon(machine, world)
    poke_cell(machine, recorder, 'C', 0, 1000)
    poke_cell(machine, recorder, 'PW', 0, 200)
    for monster in range(1, 11):
        for distance in (1, 2, 3, 5, 8):
            for x in range(2, 10):
                poke_square(machine, recorder, x, 1, 0)
            poke_square(machine, recorder, 1 + distance, 1, 10 * monster)
            press(machine, ' ')
    return finish('gallery-10', '10', recorder)


def session_amulet_fighter() -> dict:
    machine, recorder, world = started_session('10', '1', 'Y', 'F', 'MSFQ')
    press(machine, 'P')
    enter_first_dungeon(machine, world)
    # A thief that finds nothing to steal loops forever at line 4620, so the player carries plenty.
    poke_cell(machine, recorder, 'PW', 0, 200)
    rng = random.Random(21)
    for _ in range(150):
        if is_over(machine):
            press(machine, ESCAPE)
            break
        if 'TO CONT' in screen_text(machine):
            press(machine, RETURN)
        elif fight_if_attacked(machine, 'M'):
            pass
        else:
            roll = rng.random()
            if roll < 0.35:
                press(machine, FORWARD)
            elif roll < 0.45:
                press(machine, rng.choice([TURN_RIGHT, TURN_LEFT]))
            elif roll < 0.55:
                press(machine, 'X')
            else:
                press(machine, 'A', 'M')
    return finish('amulet-f-10', '10', recorder)


def session_amulet_mage() -> dict:
    machine, recorder, world = started_session('10', '1', 'Y', 'M', 'MSFQ')
    enter_first_dungeon(machine, world)
    poke_cell(machine, recorder, 'PW', 0, 200)
    poke_cell(machine, recorder, 'PW', 1, 1)
    poke_cell(machine, recorder, 'PW', 4, 1)
    press(machine, 'A', 'R', 'A', 'B', 'A', 'M', '4', 'A', 'M', '4', 'A', 'M', '9', '1', 'X')
    press(machine, 'X')
    press(machine, 'A', 'M', '2', 'X')
    for choice in '3341234':
        if is_over(machine):
            break
        if 'TO CONT' in screen_text(machine):
            press(machine, RETURN)
        press(machine, 'A', 'M', choice)
    if is_over(machine):
        press(machine, ESCAPE)
    return finish('amulet-m-10', '10', recorder)


def session_traps_and_chests() -> dict:
    machine, recorder, world = started_session('10', '1', 'Y', 'F', 'RFFFFFFFFFFFFFFQ')
    enter_first_dungeon(machine, world)
    for tiles in ([5], [5], [2], [7, 9], [7, 9], [8], [8], [8]):
        if walk_to(machine, tiles) and tiles not in ([5], [2]):
            press(machine, 'X')
    if is_over(machine):
        press(machine, ESCAPE)
    return finish('traps-chests-10', '10', recorder)


def session_fleeing_monsters() -> dict:
    machine, recorder, world = started_session('10', '4', 'Y', 'F', 'RSFFFFFFFFQ')
    enter_first_dungeon(machine, world)
    poke_cell(machine, recorder, 'C', 0, 120)
    for _ in range(160):
        if is_over(machine):
            press(machine, ESCAPE)
            break
        if 'TO CONT' in screen_text(machine):
            press(machine, RETURN)
        elif not fight_if_attacked(machine, 'R'):
            press(machine, ' ')
    return finish('fleeing-10', '10', recorder)


def session_thieves_and_gremlins() -> dict:
    machine, recorder, world = started_session('12', '1', 'Y', 'F', 'RFFFFFFFFFFFFFFQ')
    enter_first_dungeon(machine, world)
    poke_cell(machine, recorder, 'C', 0, 400)
    for _ in range(6):
        if not walk_to(machine, [7, 9]):
            break
        press(machine, 'X')
    for _ in range(150):
        if is_over(machine):
            press(machine, ESCAPE)
            break
        if 'TO CONT' in screen_text(machine):
            press(machine, RETURN)
        elif not fight_if_attacked(machine, 'R'):
            press(machine, ' ')
    return finish('thieves-12', '12', recorder)


def session_starvation() -> dict:
    machine, recorder, world = started_session('3', '1', 'Y', 'F', 'FQ')
    walk, _castle = path_to(world, world['start'], 5)
    press(machine, *walk, 'X', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ\r', 'Y', ' ')
    for _ in range(40):
        if is_over(machine):
            press(machine, ESCAPE)
            break
        press(machine, ' ')
    return finish('starvation-3', '3', recorder)


def session_court() -> dict:
    machine, recorder, world = started_session('3', '1', 'Y', 'F', 'FFFFQ')
    walk, _castle = path_to(world, world['start'], 5)
    press(machine, *walk, 'X', 'MERLIN\r', 'N', ' ')
    press(machine, 'X', 'MERLIN\r', 'Y', ' ')
    press(machine, 'X', ' ')
    poke_task(machine, recorder, -3)
    press(machine, 'X', ' ')
    poke_task(machine, recorder, -3)
    press(machine, 'X', ' ')
    return finish('court-3', '3', recorder)


def session_knighthood_top_level() -> dict:
    machine, recorder, world = started_session('3', '10', 'Y', 'F', 'FFFFQ')
    walk, _castle = path_to(world, world['start'], 5)
    press(machine, *walk, 'X', 'ARTHUR\r', 'Y', ' ')
    poke_task(machine, recorder, -10)
    press(machine, 'X', ' ')
    return finish('knighthood-top-3', '3', recorder)


SCENARIOS = [session_gallery, session_amulet_fighter, session_amulet_mage, session_traps_and_chests, session_fleeing_monsters,
             session_thieves_and_gremlins, session_starvation, session_court, session_knighthood_top_level]


def main(stages: list) -> None:
    (OUT / 'sessions').mkdir(parents=True, exist_ok=True)

    if 'worlds' in stages:
        tables = None
        worlds = []
        for lucky in [str(number) for number in range(1, 31)] + ['0', '-1', '-7', '2.5', '1979', '65535']:
            machine = new_game(lucky)
            if tables is None:
                tables = record_tables(machine)
            worlds.append(record_world(machine, lucky))
            print('world', lucky, flush=True)
        (OUT / 'tables.json').write_text(json.dumps(tables, separators=(',', ':')) + '\n')
        (OUT / 'worlds.json').write_text(json.dumps(worlds, separators=(',', ':')) + '\n')

    if 'scenarios' in stages or 'gallery' in stages:
        for make in (SCENARIOS if 'scenarios' in stages else [session_gallery]):
            session = make()
            (OUT / 'sessions' / f"{session['name']}.json").write_text(json.dumps(session, separators=(',', ':')) + '\n')
            print('session', session['name'], len(session['steps']), flush=True)

    if 'input' in stages:
        records = [record_input(typed) for typed in INPUT_LINES]
        (OUT / 'input.json').write_text(json.dumps(records, separators=(',', ':')) + '\n')
        print('input', len(records), flush=True)

    if 'dungeons' in stages:
        worlds = json.loads((OUT / 'worlds.json').read_text())
        dungeons = []
        for world in worlds[:3]:
            machine = dungeon_machine(world['lucky'], '1')
            for tx, ty in squares(world, 4)[:3]:
                for level in range(1, 11):
                    record = record_dungeon(machine, tx, ty, level)
                    record['lucky'] = world['lucky']
                    dungeons.append(record)
            print('dungeons', world['lucky'], flush=True)
        (OUT / 'dungeons.json').write_text(json.dumps(dungeons, separators=(',', ':')) + '\n')

    if 'sessions' in stages or 'dungeon-sessions' in stages:
        makers = [session_creation, session_overworld, session_knighthood,
                  lambda: session_dungeon('1', 'F', 'FFFFRASBMQ', 11, 150),
                  lambda: session_dungeon('2', 'M', 'FFFFMMQ', 12, 150),
                  lambda: session_dungeon('5', 'F', 'FFFFFRQ', 13, 250)]
        for make in makers[3:] if 'dungeon-sessions' in stages else makers:
            session = make()
            (OUT / 'sessions' / f"{session['name']}.json").write_text(json.dumps(session, separators=(',', ':')) + '\n')
            print('session', session['name'], len(session['steps']), flush=True)


if __name__ == '__main__':
    main(sys.argv[1:] or ['worlds', 'dungeons', 'sessions'])
